name: Set up Jira Autolink References

on:
  workflow_dispatch:  # Permite acionar manualmente
  push:
    branches: [ main ]  # Executa ao fazer push na branch principal

jobs:
  set-jira-autolink:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Jira Autolinks
        uses: fiddlermikey/action-add-autolink@v1.0
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Token com permissões de admin
          keyPrefix: "UP-"  # Prefixo do projeto no Jira (UP-123)
          url: "https://expatcorn.atlassian.net/browse/UP-{{number}}"  # URL do Jira
