name: Sync GitHub Issues to Jira

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        uses: atlassian/gajira-create@v2.0.0
        with:
          project: UP
          issuetype: Task
          summary: ${{ github.event.issue.title }}
          description: |
            **GitHub Issue:** [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})
            **Autor:** @${{ github.event.issue.user.login }}
            
            ${{ github.event.issue.body }}
        env:
          JIRA_BASE_URL: https://expatcorn.atlassian.net
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
